### ISSUE TITLE
Getting java.net.ProtocolException: HTTP method DELETE doesn't support output

### ISSUE THREAD

**Issue by LuisMuniz** [jwagenleitner/groovy-wslite#108]
Library version 1.1.2

When using the DELETE method on a URL, I found that the HttpClient failed with the above exception.

```
Caused by: java.net.ProtocolException: HTTP method DELETE doesn't support output
        at wslite.http.HTTPClient.setupConnection(HTTPClient.groovy:118)
        at wslite.http.HTTPClient.execute(HTTPClient.groovy:54)
 ```

In fact, the underlying HttpURLConnection is a sun.net.www.protocol.http.HttpURLConnection (using oracle jdk 7), and this implementation throws this exception when getOutputStream() is called the the method is not GTE, POST, or PUT.

It seems like the easy fix would be to change HttpClient.setupConnection to avoid trying to obtain the OutputStream of the response when executing a DELETE request.

**Comment by LuisMuniz** [comment]
Any chance of someone looking at this, or should I cut my losses and go for another library?

**Comment by LuisMuniz** [comment]
Actually looking at it more closely, this seems to be due to the fact that elasticsearch has a delete by query endpoint, which requires to send a DELETE request with a data payload.

The HttpUrlConnection implementation is overzealous in refusing this kind of request.

So here we are, looking at the code it does not seem obvious to use a different implementation of HttpURLConnection. What is weird is that when I use https, the error does not happen. So I'm kind of stuck. It seems like i will have to switch to another library. Any ideas?

**Comment by LuisMuniz** [comment]
Yes, found out why when using https there is no exception:

```groovy
if(!"POST".equals(this.method) && !"PUT".equals(this.method) && "http".equals(this.url.getProtocol()))
````
The last condition makes sure that this exception is only thrown in case of http. HttpsURLConnection delegates to this class for the underlying https protocol, but escapes this case, because the protocol is https obviously.

**Comment by boekhold** [comment]
@LuisMuniz, is this still an issue? I can create a pull request that only obtains the conn.outputstream in case the request method was POST/PUT/GET...

**Comment by LuisMuniz** [comment]
Hi.

I have decided not to use this endpoint accepting DELETE with a body.
This endpoint was being deprecated anyway, indicating the possibility that this was a bad idea.
