### ISSUE TITLE
SOAPBuilder fails to build from closure

### ISSUE THREAD

**Issue by jonnybot0** [jwagenleitner/groovy-wslite#70]
I'm trying to make a simple script that can call some methods on a SOAP service of a product we use internally. However, the SOAPMessageBuilder is throwing an error.

```
Caught: groovy.lang.MissingMethodException: No signature of method: wslite.soap.SOAPMessageBuilder.soap-env:Body() is applicable for argument types: (java.util.LinkedHashMap, massDelete$_run_closure3) values: [[:], massDelete$_run_closure3@7280fe1b]
groovy.lang.MissingMethodException: No signature of method: wslite.soap.SOAPMessageBuilder.soap-env:Body() is applicable for argument types: (java.util.LinkedHashMap, massDelete$_run_closure3) values: [[:], massDelete$_run_closure3@7280fe1b]
    at wslite.soap.SOAPMessageBuilder$_toString_closure3.doCall(SOAPMessageBuilder.groovy:74)
    at wslite.soap.SOAPMessageBuilder$_toString_closure3.doCall(SOAPMessageBuilder.groovy)
    at wslite.soap.SOAPMessageBuilder.toString(SOAPMessageBuilder.groovy:71)
    at wslite.soap.SOAPMessageBuilder$toString$0.call(Unknown Source)
    at wslite.soap.SOAPClient.send(SOAPClient.groovy:44)
    at wslite.soap.SOAPClient$send.call(Unknown Source)
    at massDelete$_run_closure1.doCall(massDelete.groovy:16)
    at massDelete.run(massDelete.groovy:32)
```

Here's my script, somewhat obfuscated.

```
@Grab(group='com.github.groovy-wslite', module='groovy-wslite', version='0.8.0')
import wslite.soap.*
import groovy.xml.XmlUtil
import java.io.Console

//Define urls
def specUrl = "http://..."
def wsdlUrl = "https://...?WSDL"

def bdm = new SOAPClient(wsdlUrl)
bdm.httpClient.sslTrustAllCerts = true
def slurp = new XmlSlurper()

//Here, I'm defining a simple closure to remove a bit of the boiler plate
// involved in crafting a response
def getResponse = { soapAction, soapBody ->
    bdm.send(SOAPAction: "$specUrl/$soapAction") {
        body soapBody
    }   
}

//Get the dataSource
def dsObject = getResponse("GetDataSourceNameList",
    { GetDataSourceNameList(specUrl) } ).GetDataSourceNameListResponse.GetDataSourceNameListResult
def ds = slurp.parseText(dsObject.text()).toString()
println ds
//All of the above works-it calls the remote GetDataSourceNameList method and gets a response

//Login- here's where the trouble begins
//Read the username and password to connect to BDMS with
Console cons = System.console()
def userName = new String(cons.readLine("[%s]",["User Name: "] as Object[]))
def password = new String(cons.readPassword("[%s]",["Password: "] as Object[]))
def sessionTicket = getResponse("Login", {Login(xmlns: specUrl) {
        dataSource(ds)
        userId(userName)
        password(password)}}
    )   
    //.LoginResponse.LoginResult.text()
println sessionTicket
```

Why is the SOAPMessageBuilder trying to call some soap-env:Body() method???

**Comment by josdem** [comment]
I had the same problem, in my case was solved using delegate scope inside closures.

``` groovy
body {
  stamp('xmlns':action) {
    delegate.username(username)
    delegate.password(password)
  }
}
```
