### ISSUE TITLE
411 Length Required error while sending SOAP request

### ISSUE THREAD

**Issue by trillianC** [jwagenleitner/groovy-wslite#73]
I have a simple SOAP request that I'm sending multiple times in order to test different scenarios... some of the times (like, 1 out of 20, randomly) I get the exception:

<pre>unit.framework.AssertionFailedError: Exception occured: 411 Length Required
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1339)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:62)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:165)</pre>

This is my request:

<pre>cat_client.send(SOAPAction:'http://mytest.../GetCategory') {
			version SOAPVersion.V1_2
			envelopeAttributes 'xmlns:ser':'http://mytest.../ServiceContract',
			'xmlns:wsa':'http://www.w3.org/2005/08/addressing',
			'xmlns:cat':'http://mytest.../ServiceContract/Category'
			header {
				'ser:cat'(id)
'wsa:Action'("http://mytest.../ServiceContract/Category/ICategory/GetCategory")
			}
			body {
				'cat:GetCategoryBy' { 'cat:id'(id) }
			}
		}</pre>

Is there a way to send the content length in the request? Or, if not, how to resolve this issue? Thanks.

**Comment by UltraL0rd** [comment]
I have the exact same problem.. Has this ever been solved?

**Comment by FranPregernik** [comment]
Same here, once in a while I get the same error.

We are using v0.7.2.

**Comment by jwagenleitner** [comment]
I am not able to replicate this.  I have found that regardless of what content-length is set on the request properties it appears that the HttpURLConnection overrides this.  But in each it does send content-length to the server.
